
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvU2w6A2GhfhdNTSGYFrHbuPGujtISEOg',
    appId: '1:489840208186:web:85690811f773fb94eb4803',
    messagingSenderId: '489840208186',
    projectId: 'chatapp-75ba9',
    authDomain: 'chatapp-75ba9.firebaseapp.com',
    storageBucket: 'chatapp-75ba9.appspot.com',
    measurementId: 'G-0TRRHTNN8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMqteOXIDN6VpXLrv_mSyV9bPzpZ5sqQg',
    appId: '1:489840208186:android:36b98b59da257951eb4803',
    messagingSenderId: '489840208186',
    projectId: 'chatapp-75ba9',
    storageBucket: 'chatapp-75ba9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXfR_lFRO_rMvcI8NqG6qNqTANtzWYmIE',
    appId: '1:489840208186:ios:08a27605b6939bdfeb4803',
    messagingSenderId: '489840208186',
    projectId: 'chatapp-75ba9',
    storageBucket: 'chatapp-75ba9.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXfR_lFRO_rMvcI8NqG6qNqTANtzWYmIE',
    appId: '1:489840208186:ios:08a27605b6939bdfeb4803',
    messagingSenderId: '489840208186',
    projectId: 'chatapp-75ba9',
    storageBucket: 'chatapp-75ba9.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvU2w6A2GhfhdNTSGYFrHbuPGujtISEOg',
    appId: '1:489840208186:web:06c2042640b272aceb4803',
    messagingSenderId: '489840208186',
    projectId: 'chatapp-75ba9',
    authDomain: 'chatapp-75ba9.firebaseapp.com',
    storageBucket: 'chatapp-75ba9.appspot.com',
    measurementId: 'G-KGYJWL77Z3',
  );

}