
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0GutZvH8QT9gp815tJ3LStwxhDYra67w',
    appId: '1:316196537951:web:8855e7bb2afdcac64ebdea',
    messagingSenderId: '316196537951',
    projectId: 'chatting-app-af3bc',
    authDomain: 'chatting-app-af3bc.firebaseapp.com',
    storageBucket: 'chatting-app-af3bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWq9BPR4mUyXQCjJAgZtMa6Jr3KI1HBY8',
    appId: '1:316196537951:android:c9f249d8bb96453f4ebdea',
    messagingSenderId: '316196537951',
    projectId: 'chatting-app-af3bc',
    storageBucket: 'chatting-app-af3bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCjT00FTvI_roNUVT2B3zdVtgZ98xMpwA',
    appId: '1:316196537951:ios:ad93e82570bab9a04ebdea',
    messagingSenderId: '316196537951',
    projectId: 'chatting-app-af3bc',
    storageBucket: 'chatting-app-af3bc.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCjT00FTvI_roNUVT2B3zdVtgZ98xMpwA',
    appId: '1:316196537951:ios:ad93e82570bab9a04ebdea',
    messagingSenderId: '316196537951',
    projectId: 'chatting-app-af3bc',
    storageBucket: 'chatting-app-af3bc.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0GutZvH8QT9gp815tJ3LStwxhDYra67w',
    appId: '1:316196537951:web:53105dbf5c7e1cbe4ebdea',
    messagingSenderId: '316196537951',
    projectId: 'chatting-app-af3bc',
    authDomain: 'chatting-app-af3bc.firebaseapp.com',
    storageBucket: 'chatting-app-af3bc.appspot.com',
  );
}
